
#Constantes...
BLOCK_SNAKE	= 0
BLOCK_FEED_APPLE = 1
BLOCK_FEED_GRAPE = 2
BLOCK_FEED_LEMON = 4
BLOCK_FEED_BIRD	= 3
BLOCK_FEED_TURTLE =	5
BLOCK_FEED_MOUSE = 6

DIMENSIONS_BLOCKS =	(12,12)

PATH_BACKGROUND_MUSIC =	"./music/background-music.mp3"

INITIAL_POS_SNAKE =	(20,20)

FPS	= 15
BACKGROUND_COLOR = (0,0,0)
DIMENSIONS_SCREEN =	(600,400)
TITLE_SCREEN = "Snake Venom"
